## These variables get injected into source loops

## Timestamp
timestamp=$(echo `date`)

## Extract Filenames and FQDN from lists
UPCHECK=`echo $source | awk -F/ '{print $3}'`

## Naming
BTEMPFILE="$TEMPDIR""$BASEFILENAME".tempfile.txt
BFILETEMP="$TEMPDIR""$BASEFILENAME".filetemp.txt
BORIGINALFILETEMP="$TEMPDIR""$BASEFILENAME".original.txt
BTEMPLOCAL="$TEMPDIR""$BASEFILENAME"
BTEMPLOCALSOURCE='file://'"$BTEMPLOCAL"
SEVENSLISTDONE="$TEMPDIR""$BASEFILENAME".text
TARLISTDONE="$TEMPDIR""$BASEFILENAME".text
PARSEDFILE="$PARSEDBLACKLISTSSUBDIR""$BASEFILENAME".txt
MIRROREDFILE="$MIRROREDBLACKLISTSSUBDIR""$BASEFILENAME".txt

## Use my own mirror
MIRROREDFILEDL="$MIRROREDBLACKLISTSSUBDIRGITRAW""$BASEFILENAME".txt

BHEAVYPARSELIST="$HEAVYPARSELISTDIR""$BASEFILENAME".lst
BLIGHTPARSELIST="$LIGHTPARSELISTDIR""$BASEFILENAME".lst
BDEADPARSELIST="$DEADBLACKLSTDIR""$BASEFILENAME".lst
BIPPARSELIST="$IPLISTDIR""$BASEFILENAME".lst
WWHITETEMP="$TEMPDIR""$BASEFILENAME".whitetemp.txt
BBLACKTEMP="$TEMPDIR""$BASEFILENAME".blacktemp.txt
BMAINPARSELIST="$MAINLISTDIR""$BASEFILENAME".lst
KILLTHELIST="$BLACKLSTSTHATDIEDIR""$BASEFILENAME".list

CURRENTTLDLIST="$MIRROREDTLDLISTSSUBDIR""$BASEFILENAME".txt

LISTBASENAMETXT="$BASEFILENAME".txt

BASEFILENAMEDASHNUM=$(echo $BASEFILENAME | sed 's/[0-9\-]/ /g')
BASEFILENAMENUM=$(echo $BASEFILENAME | sed 's/[0-9]//g')
TAGTHEREPOLOG="[Details If Any]("$RECENTRUNLOGSDIRRAW""$BASEFILENAMENUM".txt)"
BNAMEPRETTYSCRIPTTEXT=$(echo $BASEFILENAMEDASHNUM)

SBNAMELOGFILE="$SPECIFICLOGSDIR""$BASEFILENAME".log

COUNTRYCODECOMPLETE="$COUNTRYCODESSUBSDIR""$BASEFILENAME".txt
